export default [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@doe.com',
    city: 'Patna, Bihar',
    date: 'Nov 2, 2023',
    views: 11,
    subtitle: 'Chhath puja 2023 in Shyam Vihar, Delhi ground reporting',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Jeremy_Meeks.jpg'),
  },
  {
    id: 2,
    name: 'Uday',
    email: 'john@doe.com',
    city: 'Delhi, India',
    date: 'Nov 11, 2023',
    views: 15,
    subtitle: 'Chhath puja 2023 in Shyam Vihar, Delhi ground reporting',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Jeremy_Meeks.jpg'),
  },
  {
    id: 3,
    name: 'Ankit',
    email: 'john@doe.com',
    city: 'Indore, Madhya Pradesh',
    date: 'Nov 10, 2023',
    views: 19,
    subtitle: 'Chhath puja 2023 in Shyam Vihar, Delhi ground reporting',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Jeremy_Meeks.jpg'),
  },
  {
    id: 4,
    name: 'Manish',
    email: 'john@doe.com',
    city: 'Samastipur, Bihar',
    date: 'Nov 21, 2023',
    views: 12,
    subtitle: 'Chhath puja 2023 in Shyam Vihar, Delhi ground reporting',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Jeremy_Meeks.jpg'),
  },
  {
    id: 5,
    name: 'Kunal',
    email: 'john@doe.com',
    city: 'Pune, Maharashtra',
    date: 'Nov 22, 2023',
    views: 1,
    subtitle: 'Chhath puja 2023 in Shyam Vihar, Delhi ground reporting',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Jeremy_Meeks.jpg'),
  },
];
