export default [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@doe.com',
    city: 'Patna, Bihar',
    date: 'Nov 2, 2023',
    views: 11,
    subtitle: 'Chhath puja 2023 in Shyam Vihar, Delhi ground reporting',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Jeremy_Meeks.jpg'),
    likes: 1,
  },
  {
    id: 2,
    name: 'Uday',
    email: 'john@doe.com',
    city: 'Delhi, India',
    date: 'Nov 11, 2023',
    views: 15,
    subtitle:
      'Put your graphic novels down and your costume on, because it’s time to head to this year’s Woodbridge Comic Con! Meet your favorite characters from television and film, buy cool gear, and show off your latest cosplay to an audience of likeminded enthusiasts.',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Justin_Bieber.jpg'),
    likes: 2,
  },
  {
    id: 3,
    name: 'Ankit',
    email: 'john@doe.com',
    city: 'Indore, Madhya Pradesh',
    date: 'Nov 10, 2023',
    views: 19,
    subtitle:
      'Love camels, wild deer, and celebrities – as well as making a difference? Join us at our safari-themed wildlife park for an evening of petting our animal friends and hanging out with other environment enthusiasts. Other World Adventures will open its doors at 4 PM on Sunday, July 14, for fun in the sun, dinner, and a live speaker – Jane Goodall herself.',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Henry_Cavill.jpg'),
    likes: 3,
  },
  {
    id: 4,
    name: 'Manish',
    email: 'john@doe.com',
    city: 'Samastipur, Bihar',
    date: 'Nov 21, 2023',
    views: 12,
    subtitle:
      'Enjoy the best of Winnipeg’s food scene at our one-day popup on February 13th, held in Cozy Carl’s Grocery from 10 AM to 2 PM. Vendors from all over the city will be in attendance, so you can enjoy everything from craft beer to poutine to Valentine’s Day goodies. Tickets are $10 for adults and $5 for children under 13, which gets you entry into the event and one free drink.',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/david.jpg'),
    likes: 4,
  },
  {
    id: 5,
    name: 'Kunal',
    email: 'john@doe.com',
    city: 'Pune, Maharashtra',
    date: 'Nov 22, 2023',
    views: 100,
    subtitle:
      'You’re already used to getting cooking tips from Giada de Laurentiis right from home, so why fix what ain’t broken? Tune in to our livestream event on Friday, December 12 at 3 PM, when the celebrity chef will share tips on cooking holiday meals that convert. Featured dishes include rack of lamb, rosemary mashed potatoes, and balsamic carrots with a surprise dessert!',
    location: 'Najafgarh New Delhi, Delhi Division, Delhi, 110043, India',
    image: require('../assets/Zayn.jpg'),
    likes: 5,
  },
];
